apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: easytravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: dynatrace/easytravel-backend
        env:
        - name: ET_DATABASE_LOCATION
          value: "mongodb:27017"
        ports:
        - containerPort: 8091
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    name: backend
  namespace: easytravel
spec:
  ports:
  - port: 8091
  selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: easytravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: dynatrace/easytravel-frontend
        env:
        - name: ET_BACKEND_URL
          value: "http://backend:8080"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    name: frontend
  namespace: easytravel
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 31012
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgen
  namespace: easytravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgen
  template:
    metadata:
      labels:
        app: loadgen
    spec:
      containers:
      - name: loadgen
        image: dynatrace/easytravel-loadgen
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: easytravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverse-proxy
  template:
    metadata:
      labels:
        app: reverse-proxy
    spec:
      containers:
      - name: nginx
        image: dynatrace/easytravel-nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: www
  labels:
    name: www
  namespace: easytravel
spec:
  ports:
  - port: 80
  selector:
    app: reverse-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: easytravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: dynatrace/easytravel-mongodb
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    name: mongodb
  namespace: easytravel
spec:
  ports:
  - port: 27017
  selector:
    app: mongodb
