apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: monitoring
data:
  prometheus.rules: |-
    groups:
    - name: devopscube demo alert
      rules:
      - alert: High Pod Meory
        expr: sum(container_memory_usage_bytes) > 1
        for: 1m
        labels:
          severity: slack
        annotations:
          summary: High Memory Usage
  prometheus.yml: |-
    global:
      scrape_interval: 20s
      evaluation_interval: 20s
    rule_files:
      - /etc/prometheus/prometheus.rules
    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets:
          - "10.1.150.150:32000"
    scrape_configs:
       - job_name: 'prometheus'
         static_configs:
            - targets: ['10.1.150.150:30000']
       - job_name: 'jenkins'
         metrics_path: /prometheus
         static_configs:
           - targets: ['10.1.150.4:8085']
       - job_name: node-exporter
         static_configs:
           - targets: ['10.1.150.126:31020']
       - job_name: 'kubernetes-apiservers'
         kubernetes_sd_configs:
         - role: endpoints
         scheme: https
         tls_config:
           ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
         bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
         relabel_configs:
         - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
           action: keep
           regex: default;kubernetes;https
       - job_name: 'kubernetes-cadvisor'
         scheme: https
         tls_config:
           ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
         bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
         kubernetes_sd_configs:
         - role: node
         relabel_configs:
         - action: labelmap
           regex: __meta_kubernetes_node_label_(.+)
         - target_label: __address__
           replacement: kubernetes.default.svc:443
         - source_labels: [__meta_kubernetes_node_name]
           regex: (.+)
           target_label: __metrics_path__
           replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
       - job_name: 'azure-monitoring'
         static_configs:
           - targets: ['10.1.150.126:9276']
       - job_name: 'cadvisor'
         static_configs:
            - targets: ['10.1.150.126:9090']
       - job_name: 'eks-monitoring'
         static_configs:
           - targets: ['10.1.150.126:9016']
       - job_name: 'kube-state-metrics'
         static_configs:
           - targets: ['10.32.0.2:8080']
       - job_name: 'blackbox'
         metrics_path: /probe
         params:
           module: [http_2xx]  # Look for a HTTP 200 response.
         static_configs:
           - targets:
              - http://10.1.150.126:31000/   # Target to probe (webpress application url) with http.
         relabel_configs:
           - source_labels: [__address__]
             target_label: __param_target
           - source_labels: [__param_target]
             target_label: instance
           - target_label: __address__
             replacement: 10.104.74.117:9115  # The blackbox exporter's real hostname:port.
      
      - job_name: 'mysqld'
         static_configs: 
         - targets: ['10.96.141.144:9104']	  
